/**
 * 插槽处理工具函数
 * 用于编译时创建动态插槽对象，处理条件插槽和循环插槽等复杂场景
 */
import { isArray } from '@vue/shared'
import type { VNode } from '../vnode'

/**
 * SSR环境下的插槽函数类型
 * #6651 在SSR的字符串推送模式下，返回值可能是undefined
 * @param args 插槽参数
 * @returns 虚拟节点数组或undefined
 */
type SSRSlot = (...args: any[]) => VNode[] | undefined

/**
 * 编译后的插槽描述符接口
 */
interface CompiledSlotDescriptor {
  /** 插槽名称 */
  name: string
  /** 插槽函数 */
  fn: SSRSlot
  /** 可选的键，用于区分条件分支 */
  key?: string
}

/**
 * 编译器运行时工具函数，用于创建动态插槽对象
 * @param slots 基础插槽对象，将被修改并返回
 * @param dynamicSlots 动态插槽数组，可以是单个插槽描述符、插槽描述符数组或undefined
 * @returns 处理后的插槽对象
 * @private
 */
export function createSlots(
  slots: Record<string, SSRSlot>,
  dynamicSlots: (
    | CompiledSlotDescriptor
    | CompiledSlotDescriptor[]
    | undefined
  )[],
): Record<string, SSRSlot> {
  // 遍历所有动态插槽
for (let i = 0; i < dynamicSlots.length; i++) {
    const slot = dynamicSlots[i]
    // array of dynamic slot generated by <template v-for="..." #[...]>
    if (isArray(slot)) {
      // 将数组中的每个插槽添加到结果对象
for (let j = 0; j < slot.length; j++) {
          slots[slot[j].name] = slot[j].fn
        }
    // 单个条件插槽，由 <template v-if="..." #foo> 生成
    } else if (slot) {
      // conditional single slot generated by <template v-if="..." #foo>
      slots[slot.name] = slot.key
        ? (...args: any[]) => {
            const res = slot.fn(...args)
            // 添加分支key，使每个条件分支被视为不同的片段
            if (res) (res as any).key = slot.key
            return res
          }
        : slot.fn
    }
  }
  return slots
}
